name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.7.2=py313hfc23b7f_100
  - anaconda-auth=0.8.6=py313haa95532_0
  - anaconda-cli-base=0.5.2=py313haa95532_0
  - anaconda_powershell_prompt=1.1.0=haa95532_1
  - anaconda_prompt=1.1.0=haa95532_1
  - annotated-types=0.6.0=py313haa95532_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=25.0.0=py313haa95532_0
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cffi=1.17.1=py313h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py313haa95532_0
  - conda=25.9.1=py313haa95532_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313haa95532_1
  - conda-content-trust=0.2.0=py313haa95532_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313haa95532_0
  - conda-package-streaming=0.12.0=py313haa95532_0
  - cpp-expected=1.1.0=h214f63a_0
  - cryptography=45.0.5=py313hcaec639_0
  - distro=1.9.0=py313haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - fmt=9.1.0=h6d14046_1
  - frozendict=2.4.2=py313haa95532_0
  - jaraco.classes=3.4.0=py313haa95532_0
  - jaraco.context=6.0.0=py313haa95532_0
  - jaraco.functools=4.1.0=py313haa95532_0
  - jsonpatch=1.33=py313haa95532_1
  - jsonpointer=3.0.0=py313haa95532_0
  - keyring=25.6.0=py313haa95532_0
  - libarchive=3.7.7=h9243413_0
  - libcurl=8.14.1=h2300eb9_1
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.16=h2bbff1b_3
  - libmamba=2.0.5=hcd6fe79_1
  - libmambapy=2.0.5=py313h214f63a_1
  - libmpdec=4.0.0=h827c3e9_0
  - libsolv=0.7.30=hf2fb9eb_1
  - libssh2=1.11.1=h2addb87_0
  - libxml2=2.13.8=h866ff63_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=2.2.0=py313haa95532_1
  - mdurl=0.1.0=py313haa95532_0
  - menuinst=2.3.1=py313h5da7b33_0
  - more-itertools=10.3.0=py313haa95532_0
  - nlohmann_json=3.11.2=h6c2663c_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pkce=1.0.3=py313haa95532_0
  - platformdirs=4.3.7=py313haa95532_0
  - pluggy=1.5.0=py313haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h827c3e9_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313haa95532_0
  - pydantic-core=2.33.2=py313h215eeae_0
  - pydantic-settings=2.6.1=py313haa95532_0
  - pygments=2.19.1=py313haa95532_0
  - pyjwt=2.10.1=py313haa95532_0
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.5=h286a616_100_cp313
  - python-dotenv=1.1.0=py313haa95532_0
  - python_abi=3.13=0_cp313
  - pywin32-ctypes=0.2.2=py313haa95532_0
  - readchar=4.0.5=py313haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.4=py313haa95532_0
  - rich=13.9.4=py313haa95532_0
  - ruamel.yaml=0.18.10=py313h827c3e9_0
  - ruamel.yaml.clib=0.2.12=py313h827c3e9_0
  - semver=3.0.2=py313haa95532_1
  - simdjson=3.10.1=h214f63a_0
  - spdlog=1.11.0=h59b6b97_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py313haa95532_0
  - tqdm=4.67.1=py313h4442805_0
  - truststore=0.10.1=py313haa95532_0
  - typer=0.9.0=py313haa95532_0
  - typing-inspection=0.4.0=py313haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml-cpp=0.8.0=hd77b12b_1
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py313h4fc1ca9_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - anyio==4.11.0
      - attrs==25.4.0
      - certifi==2025.10.5
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpickle==4.1.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupytext==1.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-venn==1.1.2
      - mdit-py-plugins==0.5.0
      - mpmath==1.3.0
      - nbformat==5.10.4
      - networkx==3.5
      - numpy==2.2.6
      - open-clip-torch==3.2.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.3
      - pillow==12.0.0
      - pip==25.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - rpds-py==0.29.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - setuptools==80.9.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - torchxrayvision==1.4.0
      - traitlets==5.14.3
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - wcwidth==0.2.14
prefix: C:\Users\yipka\miniconda3
